### PR TITLE
✅ Private database provider

### PR DESCRIPTION
**Pull request by vikas0380**
Description: Added an option to add the local or private MySQL and Postgres SQL database provider.

Changes: If the environment variable NEXT_PUBLIC_DB_PROVIDER is not specified, the default provider will be set to private.

### CODE REVIEW

**Comment by wanghaisheng** [comment]
@vikas0380   can you add sqlite support

**Comment by blefnk** [comment]
Hello and welcome, @wanghaisheng! I am already working on rewriting the project for better-sqlite3. I tried to do this a long time ago, but I had some difficulties then. I think now I have a better chance of success. This will be delivered in Relivator 1.2.6 or 1.3.0. Thank you for your interest in the project and for your patience!

**Comment by blefnk** [comment]
@vikas0380 Hi! Thank you very much for your contribution and I apologize for the late reply! I've integrated your PR into the next 1.2.6 version and also adapted it accordingly to the changes mentioned in issue #32. And also, since I'm working on adding SQLite, it doesn't require any additional installations unlike Postgres, so I'll set SQLite as the default provider. I hope for your understanding :)

**Comment by blefnk** [comment]
This feature now will be handled by [@reliverse/cli](https://github.com/reliverse/cli) 🎉

**Pull request closed without merging**
